#!/usr/bin/env bash
#
# Slice-runner for deploy-wsai.sh.
#
# The deploy script polls for up to 45 minutes and then sleeps 90 seconds
# confirming stability. The Agent SDK's Bash tool caps a single call near ten,
# so a session physically cannot foreground it: it would lose the process and
# the log with it, while the build carried on unattended on the server.
#
# This splits the wait into three cheap calls:
#
#   deploy-watch.sh start  --ref <ref> [--npm] [--pip] [--run <id>] [--attempt <n>]
#   deploy-watch.sh poll   [--slice <seconds>] [--run <id>] [--attempt <n>]
#   deploy-watch.sh status [--run <id>] [--attempt <n>]
#
# `start` launches the deploy detached and returns at once. `poll` blocks for at
# most one slice, prints everything the log gained since the previous poll, and
# says whether the deploy is still running — so nine minutes of build costs one
# turn instead of thirty, and a session that dies leaves a build that does not.
#
# Terminal state is decided by the ONESHOT_RESULT= line, not by the child
# exiting: a dropped ssh can end the local parent while the remote build runs
# on. The child's exit code is captured too, because the script exits 1 for
# unreachable, timeout AND a non-200 site, so the code alone cannot tell those
# apart.
#
# State lives under state/deploy/<run-id>/attempt-<n>.* — keyed by run and
# attempt so a second attempt never overwrites the evidence from the first,
# which is the only durable copy: /tmp on the demo box is not.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ONESHOT_HOME="${ONESHOT_HOME:-$(cd "$HERE/.." && pwd)}"
DEPLOY="$HERE/deploy-wsai.sh"

RUN_ID="${ONESHOT_RUN_ID:-manual}"
ATTEMPT="1"
REF=""
SLICE="480"
SLICE_CAP=540
POLL_SECONDS=5
FLAGS=()

usage() {
    sed -n '3,25p' "${BASH_SOURCE[0]}" | sed 's/^#\{1,2\} \{0,1\}//' >&2
    exit 2
}

need_value() {
    if [ "$#" -lt 2 ] || [ -z "${2:-}" ]; then
        echo "Missing value for $1" >&2
        exit 2
    fi
}

CMD="${1:-}"
[ "$#" -gt 0 ] && shift
case "$CMD" in
    start|poll|status) ;;
    *) usage ;;
esac

while [ "$#" -gt 0 ]; do
    case "$1" in
        --run)       need_value "$@"; RUN_ID="$2"; shift 2 ;;
        --attempt)   need_value "$@"; ATTEMPT="$2"; shift 2 ;;
        --ref)       need_value "$@"; REF="$2"; shift 2 ;;
        --slice)     need_value "$@"; SLICE="$2"; shift 2 ;;
        --npm|--pip) FLAGS+=("$1"); shift ;;
        *) echo "Unknown argument: $1" >&2; usage ;;
    esac
done

case "$ATTEMPT" in ''|*[!0-9]*) echo "--attempt must be a number" >&2; exit 2 ;; esac
case "$SLICE"   in ''|*[!0-9]*) echo "--slice must be a number" >&2; exit 2 ;; esac
[ "$SLICE" -gt "$SLICE_CAP" ] && SLICE="$SLICE_CAP"
[ "$SLICE" -lt "$POLL_SECONDS" ] && SLICE="$POLL_SECONDS"

STATE_DIR="$ONESHOT_HOME/state/deploy/$RUN_ID"
BASE="$STATE_DIR/attempt-$ATTEMPT"
LOG="$BASE.log"
PID_FILE="$BASE.pid"
OFFSET="$BASE.offset"
RUNNER="$BASE.run"

mkdir -p "$STATE_DIR"

alive() {
    local pid
    [ -f "$PID_FILE" ] || return 1
    pid="$(cat "$PID_FILE")"
    [ -n "$pid" ] || return 1
    kill -0 "$pid" 2>/dev/null
}

# sed rather than grep: with `set -o pipefail`, a grep that matches nothing
# fails the whole pipeline, and "no result line yet" is the normal case here.
last_field() { sed -n "s/^$1=//p" "$LOG" 2>/dev/null | tail -1 || true; }

log_lines() { wc -l < "$LOG" 2>/dev/null | tr -d ' ' || echo 0; }

report() {
    printf 'WATCH_STATE=%s\n' "$1"
    printf 'WATCH_RESULT=%s\n' "$(last_field ONESHOT_RESULT)"
    printf 'WATCH_EXIT=%s\n' "$(last_field ONESHOT_EXIT)"
    printf 'WATCH_PID=%s\n' "$(cat "$PID_FILE" 2>/dev/null || true)"
    printf 'WATCH_ATTEMPT=%s\n' "$ATTEMPT"
    printf 'WATCH_LOG=%s\n' "$LOG"
    printf 'WATCH_LINES=%s\n' "$(log_lines)"
}

write_runner() {
    {
        cat <<'HEADER'
#!/usr/bin/env bash
# Generated by deploy-watch.sh start. Runs the deploy once, then appends its
# exit code — which the ONESHOT_RESULT= line alone does not carry. Kept on disk
# so what was actually launched is inspectable after the fact.
HEADER
        printf 'bash %s\n' "$(printf '%q ' "$DEPLOY" --yes "$REF" ${FLAGS[@]+"${FLAGS[@]}"})"
        cat <<'FOOTER'
printf 'ONESHOT_EXIT=%s\n' "$?"
FOOTER
    } > "$RUNNER"
    chmod +x "$RUNNER"
}

cmd_start() {
    if [ -z "$REF" ]; then
        echo "start needs --ref <branch>" >&2
        exit 2
    fi
    if alive; then
        echo "Attempt $ATTEMPT is already running; not launching a second build on top of it."
        report running
        return 0
    fi

    : > "$LOG"
    : > "$OFFSET"
    write_runner

    # setsid where it exists (Linux), nohup everywhere: the build must outlive
    # both this call and the session that made it.
    if command -v setsid >/dev/null 2>&1; then
        setsid nohup "$RUNNER" >> "$LOG" 2>&1 < /dev/null &
    else
        nohup "$RUNNER" >> "$LOG" 2>&1 < /dev/null &
    fi
    printf '%s\n' "$!" > "$PID_FILE"

    echo "Launched attempt $ATTEMPT for '$REF'${FLAGS[*]:+ (${FLAGS[*]})}."
    echo "Poll it with: bash $HERE/deploy-watch.sh poll --run $RUN_ID --attempt $ATTEMPT"
    report running
}

cmd_poll() {
    local shown deadline total result
    [ -f "$LOG" ] || : > "$LOG"
    shown="$(cat "$OFFSET" 2>/dev/null || echo 0)"
    case "$shown" in ''|*[!0-9]*) shown=0 ;; esac
    deadline=$(( $(date +%s) + SLICE ))

    while :; do
        total="$(log_lines)"
        if [ "${total:-0}" -gt "$shown" ]; then
            tail -n +$(( shown + 1 )) "$LOG"
            shown="$total"
            printf '%s\n' "$shown" > "$OFFSET"
        fi

        result="$(last_field ONESHOT_RESULT)"
        if [ -n "$result" ]; then
            report terminal
            return 0
        fi
        if ! alive; then
            # No result line and no process: the script died before it could
            # say why. The log tail above is the only account there will be.
            report terminal
            return 0
        fi
        if [ "$(date +%s)" -ge "$deadline" ]; then
            report running
            return 0
        fi
        sleep "$POLL_SECONDS"
    done
}

cmd_status() {
    [ -f "$LOG" ] || : > "$LOG"
    if [ -n "$(last_field ONESHOT_RESULT)" ] || ! alive; then
        report terminal
    else
        report running
    fi
    tail -n 20 "$LOG"
}

case "$CMD" in
    start)  cmd_start ;;
    poll)   cmd_poll ;;
    status) cmd_status ;;
esac
